#!/usr/bin/env bash

echo "Ensure caching"
echo
bun install

echo
echo "Clear the node_modules only"
echo
du -sh ~/.bun/install/cache && \
du -sh bun.lockb && \
rm -f package-lock.json \
rm -rf node_modules/

echo
echo "Install"
echo
\time -f "Total time: %E\nCPU: %P" bun install
