#!/usr/bin/env bash

echo "Clear the install cache"
echo
rm -rf ./data/npm-cache  && \
rm -f package-lock.json && \
rm -rf node_modules/ && \
npm cache verify --cache ./data/npm-cache

echo
echo "Install"
echo
\time -f "\nTotal time: %E\nCPU: %P" npm install --cache ./data/npm-cache
